src/main/java/com/team6/finalproject/FinalProjectApplication.java, src/main/java/com/team6/finalproject/advice/exception/GlobalExceptionHandler.java, src/main/java/com/team6/finalproject/advice/exception/RestApiException.java, src/main/java/com/team6/finalproject/common/config/WebSecurityConfig.java, src/main/java/com/team6/finalproject/common/dto/ApiResponseDto.java, src/main/java/com/team6/finalproject/common/entity/Timestamped.java, src/main/resources/application.properties
1. 공용 패키지 common 패지지 생성
2. 반환 틀 ApiResponseDto 생성
3. 에러 반환을 위해 RestApiException 생성
4. Timestamped 생성
5. UTC Time Zone 설정
6. 환경변수 설정
=> [update] : 공용 파일 및 패키지 생성

.github/workflows/gradle.yml
Create gradle.yml 을 생성하여 Github Action 사용환경 세팅
=> [init] Github Action 세팅

src/main/java/com/team6/finalproject/common/config/WebSecurityConfig.java, src/main/java/com/team6/finalproject/home/controller.java, src/main/java/com/team6/finalproject/security/AuthenticationFilter.java, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/resources/templates/login.html
=> [update] : 회원가입 코드수정

build.gradle, src/main/java/com/team6/finalproject/FinalProjectApplication.java, src/main/java/com/team6/finalproject/common/config/S3Config.java, src/main/java/com/team6/finalproject/common/file/FileUploader.java, src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/dto/ProfileRequestDto.java, src/main/java/com/team6/finalproject/profile/dto/ProfileResponseDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/java/com/team6/finalproject/profile/repository/ProfileRepository.java, src/main/java/com/team6/finalproject/profile/service/ProfileService.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/main/resources/application.properties, src/test/java/com/team6/finalproject/profile/service/ProfileServiceImplTest.java
- 파일 업로드를 위한 S3Config, FilUploader 클래스, AWS 라이브러리 추가
- 구현한 기능 service 유닛테스트 작성
머지 후 실행 시 환경변수 추가 필요합니다!
=> [init] 프로필 작성/조회/수정/이미지수정 기능 구현

src/main/java/com/team6/finalproject/club/dto/ClubResponseDto.java, src/main/java/com/team6/finalproject/club/entity/Club.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/profile/dto/ProfileNickNameDto.java, src/main/java/com/team6/finalproject/profile/service/ProfileService.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java
1. 현재 인가된 유저의 프로필 닉네임을 동호회 개설 간 삽입
=> [update] 인가된 유저의 프로필 닉네임 삽입

src/test/java/com/team6/finalproject/club/service/ClubServiceImplTest.java
` when(profileService.findProfileByUserId(user.getId())).thenReturn(profile);`
해당 구문이 없어서 profile 을 찾지 못했음.
=> [refactor] : 테스트 코드 에러 해결

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/dto/InterestRequestDto.java, src/main/java/com/team6/finalproject/profile/dto/ProfileRequestDto.java, src/main/java/com/team6/finalproject/profile/dto/ProfileResponseDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/java/com/team6/finalproject/profile/profileinterest/entity/ProfileInterest.java, src/main/java/com/team6/finalproject/profile/profileinterest/repository/ProfileInterestRepository.java, src/main/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestService.java, src/main/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestServiceImpl.java, src/main/java/com/team6/finalproject/profile/service/ProfileService.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/test/java/com/team6/finalproject/profile/service/ProfileServiceImplTest.java
- ProfileInterest 엔티티, 서비스, 레포지토리 추가
- 요청 받기 위한 InterestRequestDto 추가
- 관심사 등록 저장여부 단위테스트 작성
- 프로필 등록/수정 요청 시 locate 입력 추가
- ProfileResponseDto 반환값 locate, profileInterestNames 추가
=> [init] 프로필 관심사 등록 기능 구현

build.gradle, src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/entity/Club.java, src/main/java/com/team6/finalproject/club/repository/ClubRepository.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/common/config/QueryDslConfig.java, src/test/java/com/team6/finalproject/club/service/ClubServiceImplTest.java
1. Soft - Delete 방식으로 삭제
2. 삭제를 요청하면 동호회의 isDelete 가 true 로 변환
3. QueryDsl 을 통해 isDelete = false 인 것만 조회
4. 삭제 성공 테스트 작성
5. 삭제된 동호회 조회 시 예외 발생 테스트 작성
=> [update] 동호회 삭제 기능 구현

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/entity/Club.java, src/main/java/com/team6/finalproject/club/interest/entity/InterestMajor.java, src/main/java/com/team6/finalproject/club/interest/entity/InterestMinor.java, src/main/java/com/team6/finalproject/club/repository/ClubRepository.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/test/java/com/team6/finalproject/club/service/ClubServiceImplTest.java
1. ClubReposiroyCustom 을 ClubReposiroy 에 상속
2. QueryDsl 메서드 명 변경
3. 기존에 사용하던 JPA 메서드 QueryDsl 로 대체
4. 사용하지 않는 Import 제거
=> [refactor] 동호회 조회 간 QueryDsl 적용

src/main/java/com/team6/finalproject/common/config/WebSecurityConfig.java, src/main/java/com/team6/finalproject/profile/likeclub/entity/LikeClub.java, src/main/java/com/team6/finalproject/profile/likeclub/service/LikeClubServiceImpl.java, src/main/java/com/team6/finalproject/profile/profileinterest/entity/ProfileInterest.java, src/main/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestServiceImpl.java, src/main/java/com/team6/finalproject/profile/repository/ProfileRepository.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/java/com/team6/finalproject/user/dto/InquiryRequestDto.java, src/main/java/com/team6/finalproject/user/dto/InquiryResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/entity/Inquiry.java, src/main/java/com/team6/finalproject/user/inquiry/entity/InquiryTypeEnum.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepository.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustom.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryService.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImpl.java, src/test/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImplTest.java
- InquiryTypeEnum 생성
- 1:1문의 단건 조회/전체 조회 구현
- 구현 기능 단위 테스트 작성
- LikeClub, ProfileInterest 테이블에서 중복등록 제한
- 프로필 생성 시 닉네임 중복 제한
=> [init] 1:1문의 작성/조회/수정 기능 구현

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/dto/ReadInterestMajorDto.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/common/initializer/DataInitializer.java
- queryDSL 로 주제별 조회 쿼리 작성
- 존재하지 않을 경우 예외 발생
- 새로 개설된 순으로 정렬
=> [update] 동호회 주제별 조회 기능 구현

src/main/java/com/team6/finalproject/post/controller/ClubPostController.java, src/main/java/com/team6/finalproject/post/dto/ClubPostRequestDto.java, src/main/java/com/team6/finalproject/post/dto/ClubPostResponseDto.java, src/main/java/com/team6/finalproject/post/entity/Post.java, src/main/java/com/team6/finalproject/post/enums/PostTypeEnum.java, src/main/java/com/team6/finalproject/post/service/ClubPostService.java, src/main/java/com/team6/finalproject/post/service/ClubPostServiceImpl.java
PostResponseDto -> ClubPostResponseDto
PostRequestDto -> ClubPostRequestDto
nickname 필드 추가
=> [refactor] dto 네임 수정 / 필드추가

src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/test/java/com/team6/finalproject/club/service/ClubServiceImplTest.java
=> [init] : 멤버 조회 성공 테스트 작성

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/dto/ProfileRequestDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/main/resources/templates/main.html, src/main/resources/templates/profile.html
- 카카오 우편번호 서비스 이용을 위한 profile.html 작성
- 우편번호 저장을 위한 zoneCode 필드 추가
- 프로필 생성/수정 시 입력받은 우편번호/주소지 저장
=> [init] 프로필 위치 정보 등록

src/main/java/com/team6/finalproject/profile/dto/ProfileRequestDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/main/resources/templates/profile.html
- 위도/경도 저장을 위한 latitude/longitude 필드 추가
- 프로필 생성/수정 시 입력받은 주소지의 위도/경도 저장
=> [init] 프로필 위치 위도/경도 추가 등록

build.gradle, src/main/java/com/team6/finalproject/meeting/controller/MeetingController.java, src/main/java/com/team6/finalproject/meeting/service/MeetingService.java, src/main/java/com/team6/finalproject/oAuth/service/KakaoService.java, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/java/com/team6/finalproject/sms/controller/SmsController.java, src/main/java/com/team6/finalproject/sms/dto/PhoneNumberDto.java, src/main/java/com/team6/finalproject/sms/dto/SmsCertificationDto.java, src/main/java/com/team6/finalproject/sms/service/redis/RedisService.java, src/main/java/com/team6/finalproject/sms/service/redis/RedisServiceImpl.java, src/main/java/com/team6/finalproject/sms/service/sms/SmsService.java, src/main/java/com/team6/finalproject/sms/service/sms/SmsServiceImpl.java, src/main/java/com/team6/finalproject/user/dto/SignupRequestDto.java, src/main/java/com/team6/finalproject/user/entity/User.java, src/main/java/com/team6/finalproject/user/repository/UserRepository.java, src/main/java/com/team6/finalproject/user/repository/UserRepositoryCustom.java, src/main/java/com/team6/finalproject/user/repository/UserRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/user/service/UserService.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/test/java/com/team6/finalproject/profile/likeclub/service/LikeClubServiceImplTest.java, src/test/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestServiceImplTest.java, src/test/java/com/team6/finalproject/profile/service/ProfileServiceImplTest.java, src/test/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImplTest.java
=> [init] 본인인증 메시지 발송 구현

src/main/java/com/team6/finalproject/user/dto/SignupRequestDto.java, src/main/java/com/team6/finalproject/user/entity/User.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/templates/signup.html
- User.age 필드 추가
- SignupRequestDto.age 필드 추가
- UserServiceImpl.signup 유저 객체 생성 시 age 추가
- signup.html에 휴대폰 인증 구현 전이라 회원가입 테스트 시 SignupRequestDto.phone 주석처리 해야 함
=> [update] User 연령대별 동호회 추천 기능을 위한 age 필드 추가

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/dto/ClubRequestDto.java, src/main/java/com/team6/finalproject/club/dto/ReadInterestMajorDto.java, src/main/java/com/team6/finalproject/club/entity/Club.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/profile/dto/ProfileRequestDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/java/com/team6/finalproject/profile/repository/ProfileRepository.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java, src/main/java/com/team6/finalproject/user/dto/SignupRequestDto.java, src/main/java/com/team6/finalproject/user/entity/User.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/templates/signup.html
- 사용자 프로필 위치 기준 거리순 동호회 추천
-  사용자가 등록한 관심사 기준 동호회 추천
-  사용자 연령과 동호회 연령대를 통한 동호회 추천
=> [complete] 거리순/관심사/연령대 동호회 추천 기능 구현 완료

src/main/java/com/team6/finalproject/admin/answer/controller/InquiryAnswerController.java, src/main/java/com/team6/finalproject/admin/answer/dto/AnswerRequestDto.java, src/main/java/com/team6/finalproject/admin/answer/service/InquiryAnswerService.java, src/main/java/com/team6/finalproject/admin/answer/service/InquiryAnswerServiceImpl.java, src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/java/com/team6/finalproject/user/inquiry/controller/InquiryController.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryRequestDto.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/entity/Inquiry.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepository.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustom.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryService.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImpl.java, src/test/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImplTest.java
- 답변 저장을 위한 Inquiry.answer 필드 추가
- soft-delete 적용을 위한 Inquiry.isDeleted 필드 추가
- 삭제되지 않은 데이터만 가져오기 위해 InquiryRepository의 기존 쿼리메서드 InquiryRepositoryCustomImpl에 작성
- 가독성을 위해 UserController에서 처리하던 Inquiry관련 요청 InquiryController로 이동
=> [init] 관리자 1:1문의 답변 기능

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java
1. 최소 활동점수(60점)와 정원(30%)을 충족한 동호회가 알고리즘을 탈 수 있음
2. 하루를 기준(06시)으로 증가한 가입자 수를 내침차순으로 정렬
3. Top 5 까지 선정
=> [init] :  인기 급상승 동호회 조회

src/main/java/com/team6/finalproject/admin/answer/controller/InquiryAnswerController.java, src/main/java/com/team6/finalproject/admin/answer/service/InquiryAnswerService.java, src/main/java/com/team6/finalproject/admin/answer/service/InquiryAnswerServiceImpl.java, src/main/java/com/team6/finalproject/admin/inquiry/controller/InquiryAdminController.java, src/main/java/com/team6/finalproject/admin/inquiry/dto/AnswerRequestDto.java, src/main/java/com/team6/finalproject/admin/inquiry/service/InquiryAdminService.java, src/main/java/com/team6/finalproject/admin/inquiry/service/InquiryAdminServiceImpl.java, src/main/java/com/team6/finalproject/user/inquiry/controller/InquiryController.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustom.java, src/main/java/com/team6/finalproject/user/inquiry/repository/InquiryRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryService.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImpl.java
- 1:1문의 전체 조회
- 특정 사용자의 문의 전체 조회
- 문의유형 별 전체 조회
=> 관리자 - 1:1문의 조회 기능

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/service/ProfileService.java, src/main/java/com/team6/finalproject/profile/service/ProfileServiceImpl.java
=> [update] 프로필 선택 조회 기능

src/main/java/com/team6/finalproject/meeting/controller/MeetingController.java, src/main/java/com/team6/finalproject/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/team6/finalproject/meeting/repository/MeetingRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/meeting/service/MeetingService.java
[refactor] : 미완료된 모임 조회
- 모임 날짜를 오름차순으로 정렬 함으로써 D-DAY 가 임박한 순으로 조회
=> 미완료된 모임 조회

src/main/java/com/team6/finalproject/meeting/repository/MeetingRepositoryCustomImpl.java
=> [refactor] : 완료된 모임 조회

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/likeclub/entity/LikeClub.java, src/main/java/com/team6/finalproject/profile/likeclub/repository/LikeClubRepository.java, src/main/java/com/team6/finalproject/profile/likeclub/repository/LikeClubRepositoryCustom.java, src/main/java/com/team6/finalproject/profile/likeclub/repository/LikeClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/profile/likeclub/service/LikeClubService.java, src/main/java/com/team6/finalproject/profile/likeclub/service/LikeClubServiceImpl.java
- 논리 삭제를 위한 LikeClub.isDeleted 필드 추가
- 관심 동호회 취소 요청 시 isDeleted = true 변경
- 관심 동호회 추가 요청 시 DB에 값이 존재하지 않는 경우 새로 생성 / 존재하는 경우 isDeleted = false 변경
=> [update] 관심 동호회 취소/재등록 기능

src/main/java/com/team6/finalproject/admin/repoort/service/ReportReceiptService.java, src/main/java/com/team6/finalproject/admin/repoort/service/ReportReceiptServiceImpl.java, src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/dto/ClubResponseDto.java, src/main/java/com/team6/finalproject/club/entity/Club.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/meeting/controller/MeetingController.java, src/main/java/com/team6/finalproject/meeting/dto/MeetingResponseDto.java, src/main/java/com/team6/finalproject/meeting/entity/Meeting.java, src/main/java/com/team6/finalproject/meeting/service/MeetingService.java, src/main/java/com/team6/finalproject/meeting/service/MeetingServiceImpl.java, src/main/java/com/team6/finalproject/post/dto/ClubPostResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/controller/InquiryController.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/entity/Inquiry.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryService.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImpl.java
=> [update] 모임, 동호회, 1:1 문의 간 파일 업로드 및 수정 기능 추가

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/dto/ProfileResponseDto.java, src/main/java/com/team6/finalproject/profile/entity/Profile.java, src/main/resources/static/css/own-profile.css, src/main/resources/static/js/manage-profile.js, src/main/resources/static/js/own-profile.js, src/main/resources/templates/own-profile.html
- Profile.userScore 필드 삭제
- 이미지, 닉네임, 소개글, 관심사 조회
- 메인으로 버튼과 프로필 수정 페이지로 가는 수정하기 버튼
=> [update] 자신의 프로필 조회 프론트 구현

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestService.java, src/main/java/com/team6/finalproject/profile/profileinterest/service/ProfileInterestServiceImpl.java, src/main/resources/static/css/manage-interests.css, src/main/resources/static/js/manage-interests.js, src/main/resources/templates/manage-interests.html
- 관심사 관리 페이지에 관심사 목록 출력
- 선택(여러개 선택 가능)에 따라 관심사 등록/삭제/재등록
=> 관심사 관리 프론트 구현

src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/java/com/team6/finalproject/user/entity/User.java, src/main/resources/static/js/manage-profile.js
- User-Profile 관계맵핑 순환 참조 sendError() 제거
- AuthorizationFilter -> URL, StaticResource 권한 설정
=> [refactor] sendError() 제거 / 필터 권한 설정

src/main/java/com/team6/finalproject/user/inquiry/controller/InquiryController.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryRequestDto.java, src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryResponseDto.java, src/main/java/com/team6/finalproject/user/inquiry/entity/Inquiry.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryService.java, src/main/java/com/team6/finalproject/user/inquiry/service/InquiryServiceImpl.java, src/main/resources/static/css/all-inquiry.css, src/main/resources/static/css/manage-inquiry.css, src/main/resources/static/js/inquiry-detail.js, src/main/resources/static/js/manage-inquiry.js, src/main/resources/templates/all-inquiry.html, src/main/resources/templates/inquiry-detail.html, src/main/resources/templates/login.html, src/main/resources/templates/manage-inquiry.html
- 1:1문의 작성/수정 페이지 구현, 서버 연결 완료
- 1:1문의 목록 조회, 상세 조회  css 미완성
=> [init] 1:1문의 작성/수정 프론트 구현

src/main/java/com/team6/finalproject/user/inquiry/dto/InquiryResponseDto.java, src/main/resources/static/css/all-inquiry.css, src/main/resources/static/css/inquiry-detail.css, src/main/resources/static/js/inquiry-detail.js, src/main/resources/static/js/manage-inquiry.js, src/main/resources/templates/all-inquiry.html, src/main/resources/templates/inquiry-detail.html
- 1:1문의 목록 조회, 상세 조회 페이지 구성, 서버 연결
- 문의 상세 조회 페이지에서 수정 버튼 클릭 시 문의 수정 페이지로 이동
- 문의 상세 조회 페이지의 삭제 버튼으로 삭제 가능
=> [complete] 1:1문의 프론트 구현 완료

src/main/java/com/team6/finalproject/common/file/FileUploader.java, src/main/resources/static/css/all-inquiry.css, src/main/resources/static/js/manage-inquiry.js, src/main/resources/templates/all-inquiry.html
- 이미지파일 선택하지 않을 시 들어가는 기본이미지(meets)로고 key 수정
- 문의 목록 조회 시 메인버튼 문의작성 페이지로 넘어가는 문의하기 버튼으로 수정
=> [update] 기본이미지 수정 / 문의 목록 조회 버튼 수정

src/main/java/com/team6/finalproject/meeting_user/dto/MeetingUsersResponseDto.java, src/main/resources/static/css/meeting-detail.css, src/main/resources/templates/meeting-detail.html
- '수정하기' 버튼 기능 구현, /meeting-update로 리다이렉트.
- '수정하기'와 '삭제하기' 버튼을 모임 작성자에게만 표시.
- 각 member-card에 클릭 이벤트 추가, 사용자의 프로필로 리다이렉트.
- 더 나은 사용자 경험을 위해 member-card에 포인터 커서 및 focus/active 효과 개선.
=> [update] 모임-상세 페이지에 UI 개선 및 상호작용 추가

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/dto/ClubResponseDto.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustom.java, src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/club/service/ClubService.java, src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/resources/static/css/my-club.css, src/main/resources/static/js/all-inquiry.js, src/main/resources/static/js/my-club.js, src/main/resources/templates/my-club.html
- ClubResponseDto 생성자 수정, 호출하던 로직들 수정
- 개설한 동호회 목록 조회 서버 로직 추가
- 개설한 동호회 목록 조회 출력을 위한 html,css,js 구현
=> [init] 개설한 동호회 목록 조회

src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/java/com/team6/finalproject/user/dto/UpdatePasswordDto.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/static/css/update-password.css, src/main/resources/static/js/update-password.js, src/main/resources/templates/update-password.html
- 현재 비밀번호, 새 비밀번호, 새 비밀번호 확인 입력받아 요청
- 비밀번호에 ID 포함 불가
- 새 비밀번호와 비밀번호 확인 불일치 시 메세지 반환
=> [init] 비밀번호 변경 프론트 구현

src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/resources/static/css/all-inquiry.css, src/main/resources/static/css/my-club.css, src/main/resources/static/css/my-page.css, src/main/resources/static/js/my-page.js, src/main/resources/static/js/my-profile.js, src/main/resources/templates/my-page.html, src/main/resources/templates/my-profile.html
- 버튼 스타일의 선택 링크
- 내 프로필 -> 프로필 페이지 -> 수정하기 버튼 -> 수정 페이지
- 가입한/개설한/찜한 동호회 -> 목록 출력 후 클릭 시 동호회 상세 페이지 이동
- 비밀번호 변경 -> 비밀번호 변경 페이지
1. 목록 페이지에서 문의하기 버튼 -> 문의 작성 페이지
2. 목록 페이지에서 제목 클릭 -> 문의 상세 페이지 -> 수정버튼 / 삭제버튼 통해 수정/삭제
=> [complete] 마이 페이지 프론트 구현

src/main/resources/static/css/my-page.css, src/main/resources/templates/my-page.html
- 관심사 관리 버튼 추가 -> 관심사 관리 페이지로 이동 -> 관심사 선택(다수 선택 가능), 저장
=> [update] 마이 페이지 관심사 관리 추가

src/main/java/com/team6/finalproject/club/apply/service/ApplyJoinClubServiceImpl.java, src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/club/dto/ClubResponseDto.java, src/main/java/com/team6/finalproject/club/member/dto/MemberInquiryDto.java, src/main/java/com/team6/finalproject/comment/service/CommentServiceImpl.java, src/main/java/com/team6/finalproject/meeting/controller/MeetingController.java, src/main/java/com/team6/finalproject/meeting/dto/MeetingResponseDto.java, src/main/java/com/team6/finalproject/meeting/entity/Meeting.java, src/main/java/com/team6/finalproject/meeting/service/MeetingService.java, src/main/java/com/team6/finalproject/meeting/service/MeetingServiceImpl.java, src/main/java/com/team6/finalproject/meeting_user/dto/MeetingUsersResponseDto.java, src/main/java/com/team6/finalproject/report/service/ReportServiceImpl.java, src/main/resources/static/css/club-detail.css, src/main/resources/templates/club-detail.html, src/main/resources/templates/meeting-detail.html
- 멤버 상태 및 신청 상태를 기반으로 가입 버튼의 텍스트와 상태 업데이트.
- 회원 상태에 따라 '모임 생성' 및 '가입' 버튼의 가시성 전환.
- 프로필 버튼 클릭 시 사용자 프로필로 리디렉션 추가.
- 적절한 피드백 메시지와 함께 로그아웃 기능 구현.
- 상태 알림과 함께 클럽 가입 기능 처리.
- 회의가 없을 때 '일정 없음' 메시지 표시.
- 세부 사항으로 이동을 위한 회의 카드에 클릭 이벤트 추가.
- 비회원에게 완료된 회의 세부 정보 접근 제한.
- 동호회장의 별명 옆에 동호회장 아이콘 표시.👑
- 모임장의 별명 옆에 모임장 아이콘 표 🌟
- 신청자 또는 회원을 클릭하여 프로필 탐색 허용.
- 선택한 이미지 파일의 이름을 입력 필드에 반영.
- 필수 필드에 대한 유효성 검사 구현.
- 회의 세부 사항 및 파일 데이터 수집을 위해 FormData 사용.
- 사용자 경험 향상을 위한 모달에 드래그 기능 추가.
=> [update] : 사용자 상호 작용을 위한 프론트엔드 향상 구현

src/main/resources/static/css/club-detail.css
16 : 9 비율로 조정
이미지가 정 가운데 오게 설정
=> [refactor] 사진 비율 조정

src/main/java/com/team6/finalproject/common/email/EmailAuth.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/static/css/my-page.css, src/main/resources/templates/my-page.html
- 회원탈퇴 링크 버튼 추가 -> 회원탈퇴 페이지 이동
- emailAuth 패키지 이동
=> [update] 마이 페이지 회원탈퇴

src/main/resources/static/js/update-password.js
- 비밀번호 변경 요청 제한사항에 걸려 예외 발생 시 해당 에러메세지 출력하도록 수정
=> [update] 비밀번호 변경 요청 예외 반환

src/main/java/com/team6/finalproject/home/controller.java, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/java/com/team6/finalproject/user/controller/UserController.java, src/main/java/com/team6/finalproject/user/dto/ResetPasswordDto.java, src/main/java/com/team6/finalproject/user/repository/UserRepository.java, src/main/java/com/team6/finalproject/user/service/UserService.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/templates/findId.html, src/main/resources/templates/findPassword.html, src/main/resources/templates/findidlist.html, src/main/resources/templates/login.html, src/main/resources/templates/resetpassword.html
=>  feature/162/findpassword

.github/workflows/gradle.yml, appspec.yml, scripts/start.sh, scripts/stop.sh
- Gradle.yml 코드 추가
- appspec.yml 파일 추가
- AppSpec Hooks 에서 실행할 start.sh, stop.sh 스크립트 파일 추가
=> [init] Github Actions 배포 자동화 적용

src/main/resources/static/css/manage-profile.css, src/main/resources/static/css/my-profile.css, src/main/resources/static/js/club-detail.js, src/main/resources/static/js/my-profile.js, src/main/resources/templates/club-detail.html, src/main/resources/templates/manage-profile.html, src/main/resources/templates/my-profile.html
1. 내 프로필 보기 디자인
2. 내 프로필 수정 디자인
-> 중간 커밋, 미완성
=> [refactor] 프론트엔드

src/main/java/com/team6/finalproject/security/AuthorizationFilter.java
"/sub-main", "/api가/clubs/get" 필터를 타지 않고, 해당 API 는 접속 가능
=> [refactor] 인가 API 추가

src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/resources/templates/login.html, src/main/resources/templates/my-club.html
- 로그인 폼에 이벤트 리스너 추가하여 기본 폼 제출 방지
- 입력된 사용자 이름과 비밀번호로 POST 요청을 보내기 위해 fetch API 사용
- 로그인 성공 시 ‘/sub-main’으로 리다이렉션 처리
- 서버 응답에 따라 적절한 알림 표시
=> fetch API를 이용한 비동기 로그인 구현

.github/workflows/deploy.yml, .github/workflows/gradle.yml, .gitignore, appspec.yml, src/main/resources/application-oauth.properties, src/main/resources/application.properties
- gradle.yml CD application.properties, application-oauth.properties 추가
- .gitignore application.properties, application-oauth.properties 추가
=> [init] gradle.yml CD application.properties 추가

.github/workflows/deploy.yml, build.gradle, scripts/start.sh, scripts/stop.sh
- 빌드 시 plain.jar 파일 생성하지 않도록 build.gradle 설정 추가
- deploy.yml JDK 세팅, 빌드 버전 수정
- start.sh, stop.sh JAR_FILE 파일명 수정
- start.sh jar 파일 실행 스크립트 수정
=> [update] 배포 자동화 코드 수정

src/main/java/com/team6/finalproject/common/config/WebSecurityConfig.java, src/main/java/com/team6/finalproject/home/controller.java, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/resources/static/css/club-detail.css, src/main/resources/templates/club-detail.html, src/main/resources/templates/login.html
- sub-main 페이지를 최초 로드 페이지로 설정하기 위해 AuthorizationFilter 수정
- 동호회 상세페이지 툴팁 설정
=> [refactor] : 최초 페이지 메인으로 구현 및 툴팁 일부 설정

src/main/java/com/team6/finalproject/club/service/ClubServiceImpl.java, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/static/js/signup.js, src/main/resources/templates/my-club.html, src/main/resources/templates/signup.html
- 기존 대문자 필수 포함에서, 선택 포함으로 변경
- ID / PW 찾기 필터 제외
- SMS 전송 및 체크 필터 제외
=> [refactor] : PW 정규식 변경 및 필터 인가 처리 개선

src/main/resources/static/js/manage-profile.js, src/main/resources/static/js/openClub.js, src/main/resources/static/js/profile.js, src/main/resources/templates/sub-main.html
- 서브메인의 프로필 버튼을 마이페이지로 이동하게 수정
- 프로필 생성 및 수정 후 서브 메인으로 리다이렉트
- 동호회 개설 후 서브 메인으로 리다이렉트
=> [refactor] : 서브 메인, 프로필, 동호회 개설 기능 개선

src/main/java/com/team6/finalproject/security/AuthorizationFilter.java
=> [refactor] : ID / PW 인증 필터 수정

.github/workflows/deploy.yml, src/main/java/com/team6/finalproject/security/AuthorizationFilter.java, src/main/resources/templates/login.html
[[update] 배포 브랜치 변경 -main](https://github.com/sepang-pang/Final-Project/commit/1209e73996623ac377c98fd494f3f3f53f8f5921)
=> [update] 배포 브랜치 변경 -main

src/main/resources/static/js/manage-profile.js, src/main/resources/static/js/my-page.js, src/main/resources/templates/manage-profile.html
=> 마이페이지 뒤로가기 버튼 개선

src/main/resources/static/js/manage-interests.js, src/main/resources/static/js/update-password.js, src/main/resources/templates/manage-profile.html, src/main/resources/templates/withdrawal.html
=> [refactor] : 리다이렉트 수정

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/resources/static/css/club-detail.css, src/main/resources/static/js/openClub.js, src/main/resources/templates/club-detail.html, src/main/resources/templates/club-update.html, src/main/resources/templates/openClub.html
- 수정 버튼은 서비스 준비중 (백엔드에서 코드는 준비됨)
- 삭제 버튼 구현
- 동호회 개설 간 위도, 경도 값을 받아오도록 설정
=> [refactor] : 수정, 삭제 버튼 구현 / 동호회 개설 간 위치값 로드

src/main/java/com/team6/finalproject/profile/controller/ProfileController.java
- 백 로직에서 try  catch 로 프로필이 존재할시에는 my-frofile 을 반환하고, 예외가 발생할 떄는 프로필 작성는 페이지로 이동하도록 개선
=> [refactor] 프로필 미작성자가 프로필 조회 불가 기능 개선

src/main/java/com/team6/finalproject/club/repository/ClubRepositoryCustomImpl.java, src/main/java/com/team6/finalproject/profile/controller/ProfileController.java
백 로직에서 try  catch 로 프로필이 존재할시에는 my-frofile 을 반환하고, 예외가 발생할 떄는 프로필 작성는 페이지로 이동하도록 개선
=> Meets v2.1

src/main/java/com/team6/finalproject/club/controller/ClubController.java, src/main/java/com/team6/finalproject/profile/controller/ProfileController.java, src/main/resources/templates/club-detail.html, src/main/resources/templates/sub-main.html
=> Meets v2.2

src/main/resources/static/js/openClub.js, src/main/resources/templates/club-detail.html
=> [refactor] 동호회 가입신청 후 반환페이지 수정

src/main/java/com/team6/finalproject/user/service/UserServiceImpl.java, src/main/resources/static/js/signup.js
- 중복된 ID 에러메세지 반환하는 것 확인했습니다.
- 회원가입 요청 시 phoneNumber를 입력한 후 인증번호 보내기를 누르지 않고 sign up 버튼을 눌러 요청하면 그냥 가입이 되어버립니다.
- redis에 값이 아예 없어서 그런지 UserService의 인증번호 일치여부 조건을 타지 않는 것으로 보입니다.
=> [refactor] 회원가입 실패 시 에러메세지 반환
